use("myDatabase")
db.createCollection("myCollection")
db.myCollection.insertOne({ name: "Alice", age: 30 })
db.myCollection.insertOne({ name: "Bob", age: 25 })
db.myCollection.insertOne({ name: "Charlie", age: 35 })
db.myCollection.find({ age: { $gt: 30 } })
db.myCollection.updateOne({ name: "Alice" }, { $set: { age: 31 } })
db.myCollection.deleteOne({ name: "Bob" })
db.myCollection.find()
